name: CI/CD Portfolio
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            if [ ! -d "portfolio" ]; then
              git clone https://github.com/RafaelKC/rkc.git portfolio
            fi
            cd portfolio
            git pull origin main
            docker build -t portfolio-site .
            docker compose down
            docker compose up -d
            docker image prune -f